#!/usr/bin/env python3
# ============================================================================
#  gen_blob_headers.py  -  Embed the trained blobs into the Arduino sketch.
#
#  Converts esp32/models/*.bin into C headers (const uint8_t arrays in flash
#  space) so the firmware carries its models and no separate LittleFS upload
#  is needed. Drop the generated *_bin_data.h next to the sketch's .ino.
#
#  Usage:  python gen_blob_headers.py
#  Output: <sketch_folder>/face_saliency_bin_data.h
#          <sketch_folder>/face_bnn_bin_data.h
#
#  The arrays are PROGMEM so the ESP32 keeps them in flash (DROM), not in the
#  scarce internal RAM; the firmware casts them to float* (they are emitted
#  byte-by-byte so alignment is not guaranteed -> see model.cpp parse, which
#  copies nothing, it just needs the buffer base to be 4-aligned).
# ============================================================================
import os
import struct as _s

_HERE = os.path.dirname(os.path.abspath(__file__))
_MODELS = os.path.normpath(os.path.join(_HERE, "..", "..", "models"))

# (source basename, macro prefix, header filename)
BLOBS = [
    ("face_saliency.bin", "FACE_SALIENCY", "face_saliency_bin_data.h"),
    ("face_bnn_student.bin", "FACE_BNN",   "face_bnn_bin_data.h"),
]


def to_header(src_path, prefix, out_path):
    with open(src_path, "rb") as fh:
        data = fh.read()
    assert len(data) % 4 == 0, f"{src_path}: size {len(data)} not multiple of 4"

    # emit as uint8_t array; model.cpp casts the base pointer to float*.
    lines = [
        f"// AUTO-GENERATED by gen_blob_headers.py -- do not edit.",
        f"// Source: {os.path.basename(src_path)}  ({len(data)} bytes = {len(data)//4} floats)",
        f"#pragma once",
        f"#include <Arduino.h>",
        f"",
        f"#define {prefix}_BYTES  {len(data)}",
        f"",
        f"PROGMEM const uint8_t {prefix.lower()}_data[{len(data)}] __attribute__((aligned(4))) = {{",
    ]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) == 16:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {out_path} ({len(data)} bytes)")


def main():
    os.makedirs(_MODELS, exist_ok=True)
    for name, prefix, header in BLOBS:
        src = os.path.join(_MODELS, name)
        if not os.path.isfile(src):
            print(f"SKIP missing {src}")
            continue
        to_header(src, prefix, os.path.join(_HERE, header))


if __name__ == "__main__":
    main()