
// ============================================================================
//  model.h - Typed access to the two trained blobs, now EMBEDDED in flash
//            (PROGMEM arrays generated by gen_blob_headers.py). Byte layout is
//            fixed by the exporter (see esp32/blobio/verify_blobs_final.py):
//
//   face_saliency.bin:   c1w(8,3,3,3) c1b(8) c2w(4,8,3,3) c2b(4)
//                        fc1w(16,12) fc1b(16) fc2w(1,16) fc2b(1)     [2964 B]
//   face_bnn_student.bin:b1w(24,3,3,3) b1b(24) b2w(40,24,3,3) b2b(40)
//                        fc1b(96) fc1s(96) fc1w8(96,1960) int8
//                        fc2w(2,96) fc2b(2)                         [227112 B]
//   NOTE: the distilled student has NO box-head (fc3 is folded into the
//   adaptive window on-device), so the blob is ~4x smaller than the teacher.
// ============================================================================
#pragma once
#include <Arduino.h>
#include <stdint.h>

struct SaliencyModel {
  const uint8_t* raw = nullptr;    // PROGMEM base of the whole blob
  const float* c1w;            // (8,3,3,3)
  const float* c1b;            // (8)
  const float* c2w;            // (4,8,3,3)
  const float* c2b;            // (4)
  const float* fc1w;           // (16,12) hidden weights
  const float* fc1b;           // (16)    hidden bias
  const float* fc2w;           // (1,16)  output weights
  const float* fc2b;           // (1)     output bias
};

struct BnnModel {
  const uint8_t* raw = nullptr;    // PROGMEM base of the whole blob
  const float*  b1w;           // (24,3,3,3)
  const float*  b1b;           // (24)
  const float*  b2w;           // (40,24,3,3)
  const float*  b2b;           // (40)
  const float*  fc1b;          // (96)
  const float*  fc1s;          // (96) per-row dequant scale
  const int8_t* fc1w8;         // (96,1960) quantized int8
  const float*  fc2w;          // (2,96)
  const float*  fc2b;          // (2)
};

// One folded conv layer (BN already folded into w/b; head has b == nullptr).
struct BSLayer {
  const float* w;
  const float* b;
};

// Linear-Bottleneck saliency (ConvBottleneckSaliency): pure conv net, outputs
// the 8x8 saliency LOGITS directly (sigmoid applied in nn_saliency_bottleneck).
// Block order (expand/dw/proj per inverted-residual):
//   stem(8,3,3,3) ir1{exp(16,8,1,1) dw(16,1,3,3,s2) proj(8,16,1,1)}
//   ir2{exp(16,8,1,1) dw(16,1,3,3,s2) proj(12,16,1,1)}
//   ir3{exp(24,12,1,1) dw(24,1,3,3,s2) proj(12,24,1,1)}
//   ir4{exp(24,12,1,1) dw(24,1,3,3,s1) proj(8,24,1,1)}
//   head(1,8,1,1, no bias)
struct BottleneckSaliencyModel {
  const uint8_t* raw = nullptr;    // PROGMEM base of the whole blob
  BSLayer stem;
  BSLayer ir1e, ir1d, ir1p;
  BSLayer ir2e, ir2d, ir2p;
  BSLayer ir3e, ir3d, ir3p;
  BSLayer ir4e, ir4d, ir4p;
  BSLayer head;
};

// Global model instances (defined in model.cpp).
extern SaliencyModel g_sal;
extern BnnModel      g_bnn;
extern BottleneckSaliencyModel g_bn_sal;

// Mount LittleFS. Returns false on failure.
bool storage_begin();

// True when the embedded blobs are available (always true for the baked-in
// build; kept for compatibility with the old LittleFS upload path).
bool model_files_present();

// Parse both embedded blobs (PROGMEM). Returns false on size- or layout-checks.
bool model_load_all();

// True once both blobs were successfully parsed (g_bnn/g_sal pointers are
// non-null). Cheap in-memory check for tasks that consume the model; do NOT
// dereference the model pointers unless this returns true.
bool nn_model_ready();

// Legacy LittleFS persistence used by the /upload endpoint. Blobs are now
// embedded, so this always returns -1 (upload path is disabled).
int  model_store_file(const char* path, const uint8_t* data, size_t len);

// Embedded blobs live in flash; there is nothing to free.
void model_free_all();