// ============================================================================
//  model.h  -  Typed access to the two trained blobs, now EMBEDDED in flash
//              (PROGMEM arrays generated by gen_blob_headers.py). Byte layout
//              is fixed by the exporter (see esp32/blobio/verify_blobs_final.py):
//
//   face_saliency.bin: c1w(8,3,3,3) c1b(8) c2w(4,8,3,3) c2b(4)
//                      fc1w(16,12) fc1b(16) fc2w(1,16) fc2b(1)     [2964 B]
//   face_bnn.bin:      b1w(40,3,3,3) b1b(40) b2w(80,40,3,3) b2b(80)
//                      fc1b(192) fc1s(192) fc1w8(192,3920) int8
//                      fc2w(2,192) fc2b(2) fc3w(4,192) fc3b(4)     [878808 B]
// ============================================================================
#pragma once
#include <Arduino.h>
#include <stdint.h>

struct SaliencyModel {
  const uint8_t* raw = nullptr;    // PROGMEM base of the whole blob
  const float* c1w;            // (8,3,3,3)
  const float* c1b;            // (8)
  const float* c2w;            // (4,8,3,3)
  const float* c2b;            // (4)
  const float* fc1w;           // (16,12) hidden weights
  const float* fc1b;           // (16)    hidden bias
  const float* fc2w;           // (1,16)  output weights
  const float* fc2b;           // (1)     output bias
};

struct BnnModel {
  const uint8_t* raw = nullptr;    // PROGMEM base of the whole blob
  const float*  b1w;           // (40,3,3,3)
  const float*  b1b;           // (40)
  const float*  b2w;           // (80,40,3,3)
  const float*  b2b;           // (80)
  const float*  fc1b;          // (192)
  const float*  fc1s;          // (192) per-row dequant scale
  const int8_t* fc1w8;         // (192,3920)
  const float*  fc2w;          // (2,192)
  const float*  fc2b;          // (2)
  const float*  fc3w;          // (4,192)
  const float*  fc3b;          // (4)
};

// Global model instances (defined in model.cpp).
extern SaliencyModel g_sal;
extern BnnModel      g_bnn;

// Mount LittleFS. Returns false on failure.
bool storage_begin();

// True when the embedded blobs are available (always true for the baked-in
// build; kept for compatibility with the old LittleFS upload path).
bool model_files_present();

// Parse both embedded blobs (PROGMEM). Returns false on size- or layout-checks.
bool model_load_all();

// True once both blobs were successfully parsed (g_bnn/g_sal pointers are
// non-null). Cheap in-memory check for tasks that consume the model; do NOT
// dereference the model pointers unless this returns true.
bool nn_model_ready();

// Legacy LittleFS persistence used by the /upload endpoint. Blobs are now
// embedded, so this always returns -1 (upload path is disabled).
int  model_store_file(const char* path, const uint8_t* data, size_t len);

// Embedded blobs live in flash; there is nothing to free.
void model_free_all();
