
// ============================================================================
//  model.cpp - Typed access to the two trained blobs, now EMBEDDED in flash
//              (PROGMEM arrays generated by gen_blob_headers.py).
// ============================================================================
#include "model.h"
#include "config.h"
#include "face_saliency_bin_data.h"
#include "face_bnn_bin_data.h"
#include <LittleFS.h>

SaliencyModel g_sal;
BnnModel      g_bnn;

bool storage_begin() {
  if (LittleFS.begin(false)) return true;
  return LittleFS.begin(true);
}

bool model_files_present() { return true; }

// ----------------------------------------------------------------------------
//  Saliency-Blob: c1w(8,3,3,3) c1b(8) c2w(4,8,3,3) c2b(4)
//                 fc1w(16,12) fc1b(16) fc2w(1,16) fc2b(1)
// ----------------------------------------------------------------------------
static bool parse_saliency() {
  const uint8_t* b = face_saliency_data;   // PROGMEM base
  size_t o = 0;

  auto R = [&](size_t n) -> const float* {
    const float* r = (const float*)(b + o); o += n * 4; return r;
  };
  g_sal.raw = b;
  g_sal.c1w = R(8 * 3 * 3 * 3);   // 216
  g_sal.c1b = R(8);               // 8
  g_sal.c2w = R(4 * 8 * 3 * 3);   // 288
  g_sal.c2b = R(4);               // 4
  g_sal.fc1w = R(16 * 12);        // 192
  g_sal.fc1b = R(16);             // 16
  g_sal.fc2w = R(1 * 16);         // 16
  g_sal.fc2b = R(1);              // 1
  if (o != FACE_SALIENCY_BYTES) {
    Serial.printf("[model] saliency parse offset %u != %u\n",
                  (unsigned)o, (unsigned)FACE_SALIENCY_BYTES);
    return false;
  }
  Serial.println("[model] saliency parsed (embedded)");
  return true;
}

// ----------------------------------------------------------------------------
//  BNN-Blob (STUDENT, no box-head): b1w(24,3,3,3) b1b(24)
//             b2w(40,24,3,3) b2b(40)
//             fc1b(96) fc1s(96) fc1w8(96,1960) int8
//             fc2w(2,96) fc2b(2)
// ----------------------------------------------------------------------------
static bool parse_bnn() {
  const uint8_t* b = face_bnn_data;        // PROGMEM base
  size_t o = 0;

  auto R = [&](size_t n) -> const float* {
    const float* r = (const float*)(b + o); o += n * 4; return r;
  };
  g_bnn.raw   = b;
  g_bnn.b1w   = R(24 * 3 * 3 * 3);   // 648
  g_bnn.b1b   = R(24);               // 24
  g_bnn.b2w   = R(40 * 24 * 3 * 3);  // 8640
  g_bnn.b2b   = R(40);               // 40
  g_bnn.fc1b  = R(96);               // 96
  g_bnn.fc1s  = R(96);               // 96
  g_bnn.fc1w8 = (const int8_t*)(b + o); o += 96 * 1960;  // 188160
  g_bnn.fc2w  = R(2 * 96);           // 192
  g_bnn.fc2b  = R(2);                // 2
  if (o != FACE_BNN_BYTES) {
    Serial.printf("[model] bnn parse offset %u != %u\n",
                  (unsigned)o, (unsigned)FACE_BNN_BYTES);
    return false;
  }
  Serial.println("[model] bnn (student) parsed (embedded)");
  return true;
}

bool model_load_all() {
  return parse_saliency() && parse_bnn();
}

bool nn_model_ready() {
  return g_sal.raw != nullptr && g_bnn.raw != nullptr;
}

int model_store_file(const char* path, const uint8_t* data, size_t len) {
  (void)path; (void)data; (void)len;
  Serial.println("[model] store disabled -- blobs are embedded");
  return -1;
}

void model_free_all() {
  g_sal.raw = nullptr;
  g_bnn.raw = nullptr;
}